module.exports = {
    bootstrapCustomizations: "./styles/_bootstrap-customizations.scss",
    mainSass: "./styles/_main.scss",
    styles: {
        normalize: true,
        scaffolding: true,
        type: true,
        code: true,
        utilities: true,
        'responsive-utilities': true,
        mixins: true,
        navs: true,
        navbar: true,
        forms: true,
        buttons: true,
        grid: true,
        panels: true,
        'list-group': true,
        badges: true,
        glyphicons: true,
        labels: true,
    },
    scripts: {
    },
};
